### ISSUE TITLE
Design Catalogs table schema

### ISSUE THREAD

**Issue by dpopp07** [bartop-io/bartop#117]
Need to design the data architecture for the Catalogs table.

**Comment by dpopp07** [comment]
Here's what I have in JSON Schema notation:
```
    Catalog:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          description: Unique identifier for the user that the catalog belongs to.
        drinkIds:
          type: array
          description: List of identifiers for the drinks in the catalog.
          items:
            type: string
        id:
          type: string
          description: The database generated ID
```

**Comment by dpopp07** [comment]
Just to keep track, the latest update is to put `catalog` as a sub-property of user, with the `drinkIds` array staying the same. So the new object would look like:
```
    catalog:
      type: array
      description: List of identifiers for the drinks in the catalog.
      items:
        type: string
```

where `catalog` is a key on the User object.
